### ISSUE TITLE
Organização de README

### ISSUE THREAD

**Issue by yurikelvin** [ceciliakemiac/Viacao-Progresso#6]
Olá Ceci, gostei do README e do projeto em si. Deixo como sugestão descrever no primeiro parágrafo um resumo geral do que se trata o projeto, para ficar claro para quem ler as principais funcionalidades do "Sistema de gerenciamento e catalogação de viagens interestelares". Creio que descrever todas funcionalidades do sistema como requisitos como está hoje deixa o README um pouco poluído (embora seja bom para facilitar a revisão) e o README é a carta de apresentação do projeto (poderia deixar alguma screenshot por exemplo com uma descrição descrevendo a funcionalidade desejada). Poderia organizar por seções, e ter uma seção de Telas por exemplo, ai la teria a descrição das funcionalidades contidas nas telas.

**Comment by ceciliakemiac** [comment]
Olá Yuri, obrigada pela sugestão!
